# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-04 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advancedConfig', '0002_featureadoption_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureadoption',
            name='user',
        ),
    ]
