# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-06 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advancedConfig', '0003_remove_featureadoption_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smtpserver',
            name='user',
        ),
    ]
