# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-27 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancedConfig', '0004_remove_smtpserver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureadoption',
            name='api',
            field=models.BooleanField(default=True, verbose_name='API'),
        ),
        migrations.AddField(
            model_name='featureadoption',
            name='process_group',
            field=models.BooleanField(default=True, verbose_name='Process Group'),
        ),
    ]
