# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-05 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancedConfig', '0005_auto_20200827_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureadoption',
            name='application',
            field=models.BooleanField(default=True, verbose_name='Applications'),
        ),
        migrations.AddField(
            model_name='featureadoption',
            name='conversion_goal',
            field=models.BooleanField(default=True, verbose_name='Conversion Goal'),
        ),
        migrations.AddField(
            model_name='featureadoption',
            name='http_monitors',
            field=models.BooleanField(default=True, verbose_name='HTTP Monitors'),
        ),
        migrations.AddField(
            model_name='featureadoption',
            name='synthetic',
            field=models.BooleanField(default=True, verbose_name='Synthetic Browsers'),
        ),
    ]
